name: Go
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        platform: [linux, windows, mac]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    
    - name: Set outputs
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      id: build
      uses: josephbmanley/build-godot-action@v1.4.0
      with:
          name: packwiz
          preset: ${{ matrix.platform }}
          projectDir: "./" 
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
          name: Packwiz ${{ steps.vars.outputs.sha_short }} - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
